version: "3.8"

services:
  db:
    image: postgres:15
    container_name: notification_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  notification-service:
    build: .
    container_name: notification_service
    depends_on:
      - db
    environment:
      - TZ=UTC
    ports:
      - "8080:8080"
      - "6969:6969"
    volumes:
      - .:/app

volumes:
  pgdata: