version: '3.8'

services:
  # notification-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: notification-service
  #   ports:
  #     - "8080:8080"
  #     - "6969:6969"
  #   depends_on:
  #     - kafka
  #   environment:
  #     - KAFKA_BROKER=kafka:9092
  #     - KAFKA_TOPIC=notifications
  #     - DB_HOST=postgres
  #     - DB_USER=postgres
  #     - DB_PASSWORD=root
  #     - DB_NAME=postgres
  #     - DB_PORT=5432
  #     - DB_SSLMODE=disable
  #   volumes:
  #     - ./config:/app/config
  #     - ./pkg/email:/app/pkg/email

  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
  
  # postgres:
  #   image: postgres:15
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: