database:
  host: "localhost"
  user: "postgres"
  password: "yourpassword"
  dbname: "mydb"
  port: 5432
  sslmode: "disable"
  
smtp:
  sender_email: "email@example.com"
  username: "username"
  password: "password"

  kafka:
  ports: ["kafka:9092"]
  topic: "notifications"